version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4002:4001" 
    environment:
      - NODE_ENV=production
      - PORT=4001 
      - BOT_TOKEN=${BOT_TOKEN}
      - CRYPTO_PAY_API_TOKEN=${CRYPTO_PAY_API_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - PUBLIC_URL=${PUBLIC_URL}
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.server.rule=Host(`api.yourdomain.com`)"
      - traefik.http.routers.server.entryPoints=http
    restart: unless-stopped
    networks:
      - coolify

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
    - VITE_PORT=3000 
      - VITE_API_URL=${VITE_API_URL}
      - VITE_TELEGRAM_BOT_USERNAME=${VITE_TELEGRAM_BOT_USERNAME}
      - VITE_PUBLIC_URL=${VITE_PUBLIC_URL}
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.client.rule=Host(`app.yourdomain.com`)"
      - traefik.http.routers.client.entryPoints=http
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - coolify

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_DOMAIN=${WEBHOOK_DOMAIN}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - WEBAPP_URL=${WEBAPP_URL}
      - SERVER_URL=${SERVER_URL}
    labels:
      - coolify.managed=true
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true