version: '3.8'

services:
  client:
    build: 
      context: ./client
    env_file: ./client/.env
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  server:
    build: 
      context: ./server
    env_file: ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build: 
      context: ./bot
    env_file: ./bot/.env
    depends_on:
      - server
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongodb_data:
